services:
  projectmanager:
    build: .
    container_name: projectmanager
    ports:
      - "3333:3333"
    volumes:
      - /mnt/nas/Projects:/mnt/nas/Projects
    env_file:
      - .env
    restart: unless-stopped